name: smart_home
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  win32: ^5.12.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  fluttericon: ^2.0.0
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  ui_common:
    git: https://github.com/brocodev/ui_common.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
